#!/bin/bash
mkdir "$1depthir/test"
mkdir "$1depthir/train"
mkdir "$1normalimages/test"
mkdir "$1normalimages/train"
python3 create_train.py --dir="$1depthir/"
python3 create_train.py --dir="$1normalimages/"
mkdir "$1dataset"
mkdir "$1dataset/depthir"
mkdir "$1dataset/normalimages"
mv "$1depthir/test/" "$1dataset/depthir/test/"
mv "$1depthir/train/" "$1dataset/depthir/train/"
mv "$1normalimages/test/" "$1dataset/normalimages/test/"
mv "$1normalimages/train/" "$1dataset/normalimages/train/"
cd "$1"
zip -r "dataset.zip" "dataset/"